version: 1.0.{build}
image: Visual Studio 2019
platform: x64
init:
- cmd: ''
before_build:
- cmd: >-
    git submodule update --init --recursive

    cd build

    cmake .. -G"Visual Studio 16 2019"
build:
  project: ./build/ImFileDialogDemo.sln
  verbosity: minimal